/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import edu.esprit.dao.DAOConfirmerCompte;
import edu.esprit.util.Connexion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;

/**
 *
 * @author AvBack
 */
public class ConfirmationInscriptionPediatre extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmationInscriptionPediatre
     */
    public ConfirmationInscriptionPediatre() {
      

        initComponents();
       
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JComboBox();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        annuler = new javax.swing.JButton();
        confirmer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        image = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setTitle("Confirmation des inscriptions");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir un pédiatre" }));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 30));

        nom.setEditable(false);
        nom.setText("Nom");
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 30));

        prenom.setEditable(false);
        prenom.setText("Prénom");
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 30));

        date.setEditable(false);
        date.setText("Date d'inscription");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 30));

        annuler.setBackground(new java.awt.Color(255, 200, 0));
        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/button.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.setBorder(null);
        annuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annuler.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/button_cliclk.png"))); // NOI18N
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        getContentPane().add(annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 40));

        confirmer.setBackground(new java.awt.Color(255, 200, 0));
        confirmer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/button.png"))); // NOI18N
        confirmer.setText("Confirmer");
        confirmer.setBorder(null);
        confirmer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        confirmer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/button_cliclk.png"))); // NOI18N
        confirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerActionPerformed(evt);
            }
        });
        getContentPane().add(confirmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, 40));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(image);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 190, 240));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/confirmation.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DAOConfirmerCompte dao = new DAOConfirmerCompte();
        dao.AfficherListPediatre(dao.GetListPediatre(), id);
    }//GEN-LAST:event_formWindowOpened

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        DAOConfirmerCompte dao = new DAOConfirmerCompte();
        dao.AfficherInfoPediatre(id, nom, prenom, date, image);
    }//GEN-LAST:event_idActionPerformed

    private void confirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerActionPerformed

        DAOConfirmerCompte dao = new DAOConfirmerCompte();
        dao.AjouterPediatre(id);
        dao.AfficherListPediatre(dao.GetListPediatre(), id);
        nom.setText("Nom");
        prenom.setText("Prénom");
        date.setText("Date d'inscription");
        image.setIcon(null);
    }//GEN-LAST:event_confirmerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed

        DAOConfirmerCompte dao = new DAOConfirmerCompte();
        dao.SupprimerPediatre(id);
        dao.AfficherListPediatre(dao.GetListPediatre(), id);
        nom.setText("Nom");
        prenom.setText("Prénom");
        date.setText("Date d'inscription");
        image.setIcon(null);

    }//GEN-LAST:event_annulerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationInscriptionPediatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationInscriptionPediatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationInscriptionPediatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationInscriptionPediatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationInscriptionPediatre().setVisible(true);
              
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel bg;
    private javax.swing.JButton confirmer;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox id;
    private javax.swing.JLabel image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
    private ImageIcon format = null;
}
